# ***Numpy***

In [1]:
import numpy as np

## **난수 생성 함수**

* **np.random.**

* rand( ) randn( ) randint( ) shuffle( )

* choice( ) permutation( )

* normal( )

In [2]:
a = np.random.rand(2, 2)    # 0 ~ 1 사이에 값 랜덤
print(a)

[[0.88010133 0.78583829]
 [0.10089673 0.48145325]]


In [4]:
b = np.random.randn(2, 2)   # 평균이 0, 분산이 1 : 표준 정규 분포
print(b)

[[-0.87699237 -1.8823236 ]
 [ 0.97492467  0.63111063]]


In [38]:
c = np.random.randint(0, 10, size=5)    # 랜덤한 정수값 생성, (최소, 최대, size)
print(c)

[2 6 4 0 0]


In [11]:
c2 = np.random.randint(0, 10, size=(2, 2))
print(c2)

[[7 6]
 [5 1]]


In [39]:
d = np.arange(10)
np.random.shuffle(d)    # 원본 자체가 바뀜
print(d)

[0 7 1 4 3 9 2 8 5 6]


In [58]:
e = np.random.choice(d, 5)   # 원하는 갯수만큼 뽑음 (중복 허용)
e_false = np.random.choice(d, 5, replace=False)   # 중복 허용 X
e_percent = np.random.choice(d, 5, p=[0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0])  # 지정확률, sum = 1
e_false_percent = np.random.choice(d, 5, replace=False, p=[0.1, 0.1, 0.1, 0.1, 0.2, 0.1, 0.1, 0.1, 0.1, 0])
print(f"e: {e}")
print(f"e_false: {e_false}")
print(f"e_percent: {e_percent}")
print(f"e_false_percent: {e_false_percent}")

e: [9 7 6 5 5]
e_false: [3 5 9 1 4]
e_percent: [1 1 7 3 8]
e_false_percent: [1 7 8 3 2]


In [60]:
# permutation 순열
f = np.arange(10)
f_p = np.random.permutation(f)  # 원본 데이터 유지
print(f"f: {f}")
print(f"f_p: {f_p}")

f: [0 1 2 3 4 5 6 7 8 9]
f_p: [0 6 1 5 8 4 2 9 7 3]


In [51]:
g = np.random.normal(0, 1, 3)   # 정규분포, (평균, 표준편차, 갯수)
print(g)

[ 2.0485963  -0.99215428 -0.48038207]


# ***Pandas***

**<h3><< Pandas란 >></h3>**

- 데이터 자체를 분석, 파악
- 표
- 데이터를 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

**<h3><< Pandas 기능 순서 >></h3>**

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
- 시계열 데이터 처리
- 데이터 시각화
---
- 시계열 데이터 처리
- 데이터 시각화

In [61]:
import pandas as pd

## **1. Series(시리즈)**
- 인덱스를 지정할 수 있음

**<h3><< Series 생성 >></h3>**

In [75]:
s = pd.Series([1, 2, 3, 4]) # 리스트
print(s)    # 인덱스를 같이 출력

0    1
1    2
2    3
3    4
dtype: int64


In [72]:
s = pd.Series((1, 2, 3, 4)) # 튜플
print(s)    # 인덱스를 같이 출력

0    1
1    2
2    3
3    4
dtype: int64


In [73]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})    # 딕셔너리
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [66]:
s3 = pd.Series(5, index=[0, 1, 'a'])    # 스칼라
print(s3)

0    5
1    5
a    5
dtype: int64


In [67]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)   # 식 재활용 가능
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


**<h3><< 슬라이싱 >></h3>**

In [79]:
series = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [80]:
series[0:4]

0    1
1    2
2    3
3    4
dtype: int64

In [81]:
series[:-1]

0    1
1    2
2    3
3    4
dtype: int64

In [82]:
series[::-1]

4    5
3    4
2    3
1    2
0    1
dtype: int64

**<h3><< Boolean Indexing >></h3>**

In [83]:
print(series > 2)

0    False
1    False
2     True
3     True
4     True
dtype: bool


In [84]:
series[series > 2]

2    3
3    4
4    5
dtype: int64

In [85]:
# 5보다 작은 시리즈 만들기
series[series < 5]

0    1
1    2
2    3
3    4
dtype: int64

**<h3><< 산술연산 >></h3>**

In [89]:
print(series + 100)
print(series - 100)
print(series * 2)
print(series ** 2)
print(series / 2)
print(series // 2)
print(series % 2)

0    101
1    102
2    103
3    104
4    105
dtype: int64
0   -99
1   -98
2   -97
3   -96
4   -95
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64
0    0
1    1
2    1
3    2
4    2
dtype: int64
0    1
1    0
2    1
3    0
4    1
dtype: int64


**<h3><< Series 객체에 접근 >></h3>**


* <h4>keys -> index</h4>
* <h3>values</h3>
* <h3>items</h3>

In [90]:
series.keys # 객체 출력
'''
<bound method Series.keys of 
0    1
1    2
2    3
3    4
4    5
dtype: int64>
'''

<bound method Series.keys of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [91]:
series.values   # value 출력

array([1, 2, 3, 4, 5])

In [93]:
series.index    # index 출력

RangeIndex(start=0, stop=5, step=1)

In [95]:
series.keys()   # index 출력 (함수 실행)

RangeIndex(start=0, stop=5, step=1)

In [102]:
print(series.items())   # zip 객체 : 순회가 가능한 쌍

for index, value in series.items():
    print(f'인덱스: {index}, 데이터: {value}')

인덱스: 0, 데이터: 1
인덱스: 1, 데이터: 2
인덱스: 2, 데이터: 3
인덱스: 3, 데이터: 4
인덱스: 4, 데이터: 5



* <h3>loc, iloc -> 일반 슬라이싱과 다른 점은 DataFrame 가면 더 차이를 느낄 수 있을 듯함</h3>


In [141]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [131]:
print(s['b'])
print(s.loc['b'])   # 행에 접근, 레이블 사용하여 접근
print(s['b':'d'])
print(s.loc['b':'d'])   # 'd' 포함

20
20
b    20
c    30
d    40
dtype: int64
b    20
c    30
d    40
dtype: int64


In [112]:
print(s.iloc[1]) # (행에 기반한) 열에 접근
print(s.iloc[1:3])  # [3] 미포함

20
b    20
c    30
dtype: int64


* <h3>at, iat</h3>
* <h3>get</h3>

In [142]:
print(s.at['a'])    # at : loc 비슷, 하나의 값만 가져올 때
print(s.iat[1])     # at에 기반

10
20


In [119]:
print(s.get('e', default = -1))   # 없는 index일 경우, 없다는 것을 알려줌

-1


**<h3><< 결측값 (NaN, None) >></h3>**

- isna()
- isnull()

**NaN(Not a Number)** -> datatype = float <br/>
**None** -> datatype = none

In [147]:
import numpy as np
import pandas as pd

data = [1, 2, 3, None]

print(np.array(data))   # None으로 인식
print(pd.Series(data))  # NaN으로 인식 -> float형, 오류를 줄일 수 있음

[1 2 3 None]
0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [151]:
s = pd.Series(data)

print(s.isna())
print(s.isnull())
print(s.isnull().sum())

0    False
1    False
2    False
3     True
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool
1


In [152]:
print(s.notnull())
print(s.notnull().sum())

0     True
1     True
2     True
3    False
dtype: bool
3


**<h4>결측치 처리하기</h4>**

In [154]:
s.dropna()  # 제거

0    1.0
1    2.0
2    3.0
dtype: float64

In [155]:
s.fillna(0) # 치환

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

**<h3><< Series 함수 >></h3>**

* <h4>집계함수</h4>

In [156]:
s = pd.Series([1, 3, 5, 7, 9])

In [157]:
s.count()

5

In [159]:
print(s.min(), s.max(), s.median())

1 9 5.0


In [160]:
print(s.mean(), s.var(), s.std())

5.0 10.0 3.1622776601683795


In [162]:
print(s.describe()) # 기초 통계 내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64


## **2. DataFrame(데이터프레임)**